services:
  spring-app:
    image: car-shop-sber
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: CarShopSber
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"