version: '3.8'

services:
  postgres:
    image: postgres:14.11-alpine3.19
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: CarShopSber
    volumes:
      - vol-pg-3:/var/lib/postgresql/data
    ports:
      - "5440:5432"

  spring-app:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: CarShopSber
    ports:
      - "8081:8081"

volumes:
  vol-pg-3: {}
